/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as ExercisesExerciseRouteImport } from './routes/exercises/$exercise'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedWorkoutsIndexRouteImport } from './routes/_authed/workouts/index'
import { Route as AuthedPlansIndexRouteImport } from './routes/_authed/plans/index'
import { Route as ExercisesPPageRouteImport } from './routes/exercises/p.$page'
import { Route as AuthedWorkoutsWorkoutRouteImport } from './routes/_authed/workouts/$workout'
import { Route as AuthedPlansCreateRouteImport } from './routes/_authed/plans/create'
import { Route as AuthedWorkoutsCreateIndexRouteImport } from './routes/_authed/workouts/create/index'
import { Route as AuthedPlansPlanIndexRouteImport } from './routes/_authed/plans/$plan/index'
import { Route as AuthedWorkoutsCreateIdRouteImport } from './routes/_authed/workouts/create/$id'
import { Route as AuthedPlansPlanEditRouteImport } from './routes/_authed/plans/$plan/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseRoute = ExercisesExerciseRouteImport.update({
  id: '/exercises/$exercise',
  path: '/exercises/$exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkoutsIndexRoute = AuthedWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansIndexRoute = AuthedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthedRoute,
} as any)
const ExercisesPPageRoute = ExercisesPPageRouteImport.update({
  id: '/exercises/p/$page',
  path: '/exercises/p/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkoutsWorkoutRoute = AuthedWorkoutsWorkoutRouteImport.update({
  id: '/workouts/$workout',
  path: '/workouts/$workout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansCreateRoute = AuthedPlansCreateRouteImport.update({
  id: '/plans/create',
  path: '/plans/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsCreateIndexRoute =
  AuthedWorkoutsCreateIndexRouteImport.update({
    id: '/workouts/create/',
    path: '/workouts/create/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPlansPlanIndexRoute = AuthedPlansPlanIndexRouteImport.update({
  id: '/plans/$plan/',
  path: '/plans/$plan/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsCreateIdRoute = AuthedWorkoutsCreateIdRouteImport.update({
  id: '/workouts/create/$id',
  path: '/workouts/create/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansPlanEditRoute = AuthedPlansPlanEditRouteImport.update({
  id: '/plans/$plan/edit',
  path: '/plans/$plan/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/exercises/$exercise': typeof ExercisesExerciseRoute
  '/exercises': typeof ExercisesIndexRoute
  '/plans/create': typeof AuthedPlansCreateRoute
  '/workouts/$workout': typeof AuthedWorkoutsWorkoutRoute
  '/exercises/p/$page': typeof ExercisesPPageRoute
  '/plans': typeof AuthedPlansIndexRoute
  '/workouts': typeof AuthedWorkoutsIndexRoute
  '/plans/$plan/edit': typeof AuthedPlansPlanEditRoute
  '/workouts/create/$id': typeof AuthedWorkoutsCreateIdRoute
  '/plans/$plan': typeof AuthedPlansPlanIndexRoute
  '/workouts/create': typeof AuthedWorkoutsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/exercises/$exercise': typeof ExercisesExerciseRoute
  '/exercises': typeof ExercisesIndexRoute
  '/plans/create': typeof AuthedPlansCreateRoute
  '/workouts/$workout': typeof AuthedWorkoutsWorkoutRoute
  '/exercises/p/$page': typeof ExercisesPPageRoute
  '/plans': typeof AuthedPlansIndexRoute
  '/workouts': typeof AuthedWorkoutsIndexRoute
  '/plans/$plan/edit': typeof AuthedPlansPlanEditRoute
  '/workouts/create/$id': typeof AuthedWorkoutsCreateIdRoute
  '/plans/$plan': typeof AuthedPlansPlanIndexRoute
  '/workouts/create': typeof AuthedWorkoutsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/exercises/$exercise': typeof ExercisesExerciseRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/_authed/plans/create': typeof AuthedPlansCreateRoute
  '/_authed/workouts/$workout': typeof AuthedWorkoutsWorkoutRoute
  '/exercises/p/$page': typeof ExercisesPPageRoute
  '/_authed/plans/': typeof AuthedPlansIndexRoute
  '/_authed/workouts/': typeof AuthedWorkoutsIndexRoute
  '/_authed/plans/$plan/edit': typeof AuthedPlansPlanEditRoute
  '/_authed/workouts/create/$id': typeof AuthedWorkoutsCreateIdRoute
  '/_authed/plans/$plan/': typeof AuthedPlansPlanIndexRoute
  '/_authed/workouts/create/': typeof AuthedWorkoutsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/exercises/$exercise'
    | '/exercises'
    | '/plans/create'
    | '/workouts/$workout'
    | '/exercises/p/$page'
    | '/plans'
    | '/workouts'
    | '/plans/$plan/edit'
    | '/workouts/create/$id'
    | '/plans/$plan'
    | '/workouts/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/exercises/$exercise'
    | '/exercises'
    | '/plans/create'
    | '/workouts/$workout'
    | '/exercises/p/$page'
    | '/plans'
    | '/workouts'
    | '/plans/$plan/edit'
    | '/workouts/create/$id'
    | '/plans/$plan'
    | '/workouts/create'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/auth/callback'
    | '/exercises/$exercise'
    | '/exercises/'
    | '/_authed/plans/create'
    | '/_authed/workouts/$workout'
    | '/exercises/p/$page'
    | '/_authed/plans/'
    | '/_authed/workouts/'
    | '/_authed/plans/$plan/edit'
    | '/_authed/workouts/create/$id'
    | '/_authed/plans/$plan/'
    | '/_authed/workouts/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExercisesExerciseRoute: typeof ExercisesExerciseRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  ExercisesPPageRoute: typeof ExercisesPPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exercise': {
      id: '/exercises/$exercise'
      path: '/exercises/$exercise'
      fullPath: '/exercises/$exercise'
      preLoaderRoute: typeof ExercisesExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workouts/': {
      id: '/_authed/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthedWorkoutsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/': {
      id: '/_authed/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthedPlansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/exercises/p/$page': {
      id: '/exercises/p/$page'
      path: '/exercises/p/$page'
      fullPath: '/exercises/p/$page'
      preLoaderRoute: typeof ExercisesPPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workouts/$workout': {
      id: '/_authed/workouts/$workout'
      path: '/workouts/$workout'
      fullPath: '/workouts/$workout'
      preLoaderRoute: typeof AuthedWorkoutsWorkoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/create': {
      id: '/_authed/plans/create'
      path: '/plans/create'
      fullPath: '/plans/create'
      preLoaderRoute: typeof AuthedPlansCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/create/': {
      id: '/_authed/workouts/create/'
      path: '/workouts/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof AuthedWorkoutsCreateIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/$plan/': {
      id: '/_authed/plans/$plan/'
      path: '/plans/$plan'
      fullPath: '/plans/$plan'
      preLoaderRoute: typeof AuthedPlansPlanIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/create/$id': {
      id: '/_authed/workouts/create/$id'
      path: '/workouts/create/$id'
      fullPath: '/workouts/create/$id'
      preLoaderRoute: typeof AuthedWorkoutsCreateIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/$plan/edit': {
      id: '/_authed/plans/$plan/edit'
      path: '/plans/$plan/edit'
      fullPath: '/plans/$plan/edit'
      preLoaderRoute: typeof AuthedPlansPlanEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPlansCreateRoute: typeof AuthedPlansCreateRoute
  AuthedWorkoutsWorkoutRoute: typeof AuthedWorkoutsWorkoutRoute
  AuthedPlansIndexRoute: typeof AuthedPlansIndexRoute
  AuthedWorkoutsIndexRoute: typeof AuthedWorkoutsIndexRoute
  AuthedPlansPlanEditRoute: typeof AuthedPlansPlanEditRoute
  AuthedWorkoutsCreateIdRoute: typeof AuthedWorkoutsCreateIdRoute
  AuthedPlansPlanIndexRoute: typeof AuthedPlansPlanIndexRoute
  AuthedWorkoutsCreateIndexRoute: typeof AuthedWorkoutsCreateIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPlansCreateRoute: AuthedPlansCreateRoute,
  AuthedWorkoutsWorkoutRoute: AuthedWorkoutsWorkoutRoute,
  AuthedPlansIndexRoute: AuthedPlansIndexRoute,
  AuthedWorkoutsIndexRoute: AuthedWorkoutsIndexRoute,
  AuthedPlansPlanEditRoute: AuthedPlansPlanEditRoute,
  AuthedWorkoutsCreateIdRoute: AuthedWorkoutsCreateIdRoute,
  AuthedPlansPlanIndexRoute: AuthedPlansPlanIndexRoute,
  AuthedWorkoutsCreateIndexRoute: AuthedWorkoutsCreateIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ExercisesExerciseRoute: ExercisesExerciseRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  ExercisesPPageRoute: ExercisesPPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
